apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todoapp
type: Opaque
data:
  NAME: dG9kb2FwcF9kYg==
  USER: dG9kb2FwcF91c2Vy
  PASSWORD: MTIzNA==
  HOST: bXlzcWwtMC5teXNxbA==